[package]
name = "arya_stark"
version = "0.1.0"
edition = "2024"


[dependencies]
winterfell = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
